In [16]:
# Import Dependencies
from splinter import Browser
from bs4 import BeautifulSoup
from pprint import pprint

import pandas as pd
import numpy as np

In [17]:
# Generate the url list
base_url = 'https://www.teamrankings.com/nfl/trends/ats_trends/?range=yearly_'

# Create the years integers
year_i = int(2003)
year_f = int(2023)
years = np.arange(year_i, 1 + year_f, 1)

# Create a list for the urls
urls = []

for year in years:
    url = base_url + str(year)
    urls.append(url)
    
print(urls)

['https://www.teamrankings.com/nfl/trends/ats_trends/?range=yearly_2003', 'https://www.teamrankings.com/nfl/trends/ats_trends/?range=yearly_2004', 'https://www.teamrankings.com/nfl/trends/ats_trends/?range=yearly_2005', 'https://www.teamrankings.com/nfl/trends/ats_trends/?range=yearly_2006', 'https://www.teamrankings.com/nfl/trends/ats_trends/?range=yearly_2007', 'https://www.teamrankings.com/nfl/trends/ats_trends/?range=yearly_2008', 'https://www.teamrankings.com/nfl/trends/ats_trends/?range=yearly_2009', 'https://www.teamrankings.com/nfl/trends/ats_trends/?range=yearly_2010', 'https://www.teamrankings.com/nfl/trends/ats_trends/?range=yearly_2011', 'https://www.teamrankings.com/nfl/trends/ats_trends/?range=yearly_2012', 'https://www.teamrankings.com/nfl/trends/ats_trends/?range=yearly_2013', 'https://www.teamrankings.com/nfl/trends/ats_trends/?range=yearly_2014', 'https://www.teamrankings.com/nfl/trends/ats_trends/?range=yearly_2015', 'https://www.teamrankings.com/nfl/trends/ats_trends/?range=yearly_2016', 'https://www.teamrankings.com/nfl/trends/ats_trends/?range=yearly_2017', 'https://www.teamrankings.com/nfl/trends/ats_trends/?range=yearly_2018', 'https://www.teamrankings.com/nfl/trends/ats_trends/?range=yearly_2019', 'https://www.teamrankings.com/nfl/trends/ats_trends/?range=yearly_2020', 'https://www.teamrankings.com/nfl/trends/ats_trends/?range=yearly_2021', 'https://www.teamrankings.com/nfl/trends/ats_trends/?range=yearly_2022', 'https://www.teamrankings.com/nfl/trends/ats_trends/?range=yearly_2023']

In [18]:
# Create a Chrome browser instance
browser = Browser('chrome')

In [19]:
# Script to automate browsing for Offense
combined_data = []

# Visit each year the url list
for url in urls:  
    
    # Visit the page and create the soup object
    browser.visit(url)
    html = browser.html
    soup = BeautifulSoup(html, 'html.parser')
    
    # Scrape the tables from the page
    tables = soup.find('tbody')
    
    # Extract data from the table
    # Create an empty list
    data_list = []
    
    # Iterate through the rows in the table
    for row in tables.find_all('tr'): 
        
        # Empty list for the row data
        row_data = []

        # Iterate through the <td> tags for each cell data point in the current row
        for cell in row.find_all('td'):
            
            row_data.append(cell.get_text())

        # Append the row_data list to the data_list
        data_list.append(row_data)
            
    combined_data.extend(data_list)
    
## Create a Pandas DataFrame by using the list of rows and a list of the column names
columns = ['Team', 'ATS Record', 'Cover %', 'MOV', 'ATS']

ats_df = pd.DataFrame(combined_data, columns=columns)

# Print the File to a .csv
ats_df.to_csv('ats.csv', index=False)

In [20]:
# Add in a field for year
ats_df['year'] = ''

# Fill in the year information
years = list(range(2003, 2024))
filled_years = [year for year in years for _ in range(32)]

print(filled_years)

[2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2003, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2004, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2006, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2010, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2011, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2014, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2016, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2021, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023]

In [21]:
# Populate the filled years and preview
ats_df['year'] = filled_years

ats_df.head(50)

             Team ATS Record Cover %    MOV   ATS  year
0     New England     14-5-0   73.7%    6.6  +4.3  2003
1    Indianapolis     11-7-1   61.1%    7.3  +4.5  2003
2    Philadelphia     11-7-0   61.1%    4.4  +1.8  2003
3       Green Bay     11-7-0   61.1%    7.7  +4.6  2003
4     Kansas City     10-7-0   58.8%    8.5  +2.9  2003
5       Baltimore     10-7-0   58.8%    6.3  +5.0  2003
6         LA Rams      9-7-1   56.3%    6.6  +1.9  2003
7         Houston      9-7-0   56.3%   -7.8  -0.9  2003
8       Tennessee     10-8-0   55.6%    6.2  +3.0  2003
9   San Francisco      7-6-3   53.9%    2.9  +2.4  2003
10     Washington      8-7-1   53.3%   -5.3  -2.8  2003
11     Cincinnati      8-7-1   53.3%   -2.4  -0.1  2003
12      Minnesota      8-7-1   53.3%    3.9  +0.6  2003
13        Buffalo      8-7-1   53.3%   -2.3  -1.5  2003
14         Dallas      9-8-0   52.9%    0.6  -0.1  2003
15        Seattle      9-8-0   52.9%    4.2  +1.7  2003
16     Pittsburgh      8-8-0   50.0%   -1.7  -2.4  2003
17   Jacksonville      8-8-0   50.0%   -3.4  -0.2  2003
18        Detroit      7-7-2   50.0%   -6.8  -1.3  2003
19        Chicago      8-8-0   50.0%   -3.9  -0.2  2003
20    New Orleans      8-8-0   50.0%    0.9  +1.0  2003
21       Carolina    10-10-0   50.0%    2.7  +2.1  2003
22         Denver      8-9-0   47.1%    2.9  +0.4  2003
23          Miami      7-9-0   43.8%    3.1  +0.3  2003
24      Tampa Bay      7-9-0   43.8%    2.3  -1.4  2003
25        Atlanta      7-9-0   43.8%   -7.7  -3.4  2003
26        NY Jets      6-9-1   40.0%   -1.0  +0.4  2003
27        Arizona     6-10-0   37.5%  -14.2  -7.3  2003
28      Cleveland     6-10-0   37.5%   -4.3  -2.5  2003
29    LA Chargers     6-10-0   37.5%   -8.0  -3.8  2003
30      NY Giants     4-12-0   25.0%   -9.0  -8.1  2003
31      Las Vegas     3-13-0   18.8%   -6.8  -4.8  2003
32    LA Chargers     13-2-2   86.7%    7.6  +7.9  2004
33        Buffalo     11-5-0   68.8%    6.9  +6.4  2004
34    New England     12-6-1   66.7%   11.1  +4.7  2004
35   Philadelphia     12-7-0   63.2%    8.1  +2.6  2004
36   Jacksonville     10-6-0   62.5%   -1.2  -0.1  2004
37       Carolina     10-6-0   62.5%    1.0  +1.4  2004
38        NY Jets     11-7-0   61.1%    4.0  +2.9  2004
39   Indianapolis     11-7-0   61.1%    9.9  +4.9  2004
40        Arizona      9-7-0   56.3%   -2.4  +1.5  2004
41      Baltimore      9-7-0   56.3%    3.1  +1.1  2004
42        Houston      9-7-0   56.3%   -1.9  +1.5  2004
43     Pittsburgh     10-8-0   55.6%    6.1  +3.3  2004
44      NY Giants      8-8-0   50.0%   -2.8  -0.1  2004
45     Washington      8-8-0   50.0%   -1.6  -0.3  2004
46        Detroit      8-8-0   50.0%   -3.4  -1.4  2004
47    New Orleans      8-8-0   50.0%   -3.6  -0.9  2004
48     Cincinnati      8-8-0   50.0%    0.1  +2.3  2004
49      Minnesota     8-10-0   44.4%    0.6  -1.9  2004